# Generated by Django 3.0 on 2021-04-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('decs', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('book_image', models.ImageField(default='default.jpg', upload_to='book_images/')),
            ],
        ),
    ]
