# Generated by Django 3.0 on 2021-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
